### ISSUE TITLE
Combat Overlay not visible in combat

### ISSUE THREAD

**Issue by franckflo** [Nazrax/fvtt-movement-planner#7]
Hi,

I am trying Combat Overlay for FVTT 10.291 and DnD 2.2.1 on Browser Opera GX. I installed the module, enabled it, then enabled the option for the overlay to always be visible in combat. 

Started a combat on a map with a grid; then pressed the Toggle Combat Overlay button. A message shows that it `is activated but is not yet visible (see settings)`. Unfortunately it never shows and I turned all the options on.

Here is a screenshot of my combat overlay settings:
![image](https://github.com/Nazrax/fvtt-combat-range-overlay/assets/80221412/70865e2a-09d7-429e-a5c0-576bfe5c8e5d)

Let me know if you need anything else to troubleshoot.

**Comment by Zamrod** [comment]
I'm trying it in DnD5e 2.2.2 and Foundry 11.305 and I also can't get it to work. It just throws constant errors in the console and prevents the token from moving. The errors in the console are:

```
libWrapper-wrapper.js:669  Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'base')
[Detected 2 packages: combat-range-overlay, lib-wrapper]
    at get weaponRangeColor [as weaponRangeColor] (tokenInfo.js:79:66)
    at Overlay.calculateTargetRangeMap (overlay.js:172:50)
    at Overlay.drawAll (overlay.js:231:33)
    at Overlay.fullRefresh (overlay.js:301:12)
    at Overlay.dragHandler (overlay.js:267:10)
    at Mouse._executeHooks (mouse.js:31:7)
    at Mouse._dragStartWrapper (mouse.js:37:10)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype._onDragLeftStart#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:31547:17)
    at #handleDragStart (foundry.js:31874:26)
    at #handleMouseMove (foundry.js:31856:37)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerMove (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerMove (earcut.js:128:75)

**Comment by sonofkyusss** [comment]
Hi,
Same issue : Nothing displayed in combat or not. All the prameters have been activated.
Console error :
tokenInfo.js:79  Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'base')
[Detected 1 package: combat-range-overlay]
    at get weaponRangeColor [as weaponRangeColor] (tokenInfo.js:79:66)
    at Overlay.calculateTargetRangeMap (overlay.js:172:50)
    at Overlay.drawAll (overlay.js:231:33)
    at Overlay.fullRefresh (overlay.js:301:12)
    at Overlay.altKeyHandler (overlay.js:273:12)
  | calculateTargetRangeMap | @ | overlay.js:172
  | drawAll | @ | overlay.js:231
  | fullRefresh | @ | overlay.js:301
  | altKeyHandler | @ | overlay.js:273

I run PF1e 9.4 on Forge/Foundry 11.306

**Comment by elpossum** [comment]
Sorry I haven't noticed this issue before as issues do not transfer to forks. This module was taken over by me June 16 2023 and is now at [this repository](https://github.com/elpossum/fvtt-combat-range-overlay). I hope this issue has been resolved since, but if it still persists, please open it again at [this page](https://github.com/elpossum/fvtt-combat-range-overlay/issues).
